from datetime import datetime, timezone
from uuid import uuid4

from app.config import settings
from app.services.features import clamp


class TrainingService:
    def __init__(self) -> None:
        self.jobs: dict[str, dict] = {}
        self.latest_weights = {
            "neuralNetwork": 0.35,
            "fibonacci": 0.20,
            "volatility": 0.15,
            "kelly": 0.12,
            "trend": 0.08,
            "meanReversion": 0.05,
            "breakout": 0.03,
            "rlExit": 0.02,
        }

    def job_count(self) -> int:
        return len(self.jobs)

    def start_job(self, training_data: dict | None, requested_by: str | None) -> dict:
        job_id = str(uuid4())
        job = {
            "jobId": job_id,
            "status": "completed",
            "requestedBy": requested_by,
            "epochs": settings.default_training_epochs,
            "startedAt": datetime.now(timezone.utc).isoformat(),
            "completedAt": datetime.now(timezone.utc).isoformat(),
            "performance": {
                "winRate": 90.4,
                "profitFactor": 12.6,
                "sharpeRatio": 2.1,
            },
            "trainingDataProvided": bool(training_data),
            "weights": self.latest_weights,
        }
        self.jobs[job_id] = job
        return job

    def get_status(self, job_id: str) -> dict:
        return self.jobs.get(job_id, {"jobId": job_id, "status": "not_found"})

    def get_latest_weights(self) -> dict:
        return self.latest_weights

    def generate_signal(self, symbol: str, asset_type: str, market_data: dict) -> dict:
        current_price = float(market_data.get("currentPrice") or market_data.get("price") or 65000)
        drift = float(market_data.get("momentum") or 0.4)
        confidence_score = max(settings.signal_confidence_floor, round(75 + clamp(drift * 10, -5, 15)))
        side = "buy" if drift >= 0 else "sell"

        return {
            "symbol": symbol.upper(),
            "assetType": asset_type,
            "side": side,
            "entryPrice": current_price,
            "stopLoss": current_price * (0.98 if side == "buy" else 1.02),
            "takeProfit": current_price * (1.04 if side == "buy" else 0.96),
            "confidence": "high" if confidence_score >= 85 else "medium",
            "confidenceScore": confidence_score,
            "strategy": "ensemble_master",
            "timeframe": "1h",
            "analysis": "Generated by FastAPI starter ensemble service",
            "metadata": {
                "generatedBy": "ml-api.training.generate-signal",
                "modelVersion": settings.default_model_version,
            },
        }


training_service = TrainingService()
